name: Playmatic E2E Tests
description: Run Playmatic E2E tests locally using the CLI
author: Playmatic

branding:
  icon: play
  color: blue

inputs:
  api-key:
    description: 'Playmatic API key'
    required: true
  environment:
    description: 'Environment from playmatic.config.ts'
    default: 'staging'
  base-url-override:
    description: 'Override baseUrl for this run'
    required: false
  test-paths:
    description: 'Test files/directories to run'
    default: 'playmatic-tests'
  cli-version:
    description: 'Playmatic CLI version'
    default: '0.1.11'
  ci-notifications:
    description: 'Enable CI notifications (defaults to true)'
    default: 'true'

outputs:
  success:
    description: 'Whether tests passed'

runs:
  using: node20
  main: dist/index.js
