name: Playmatic Autonomous Playtest
description: Run autonomous playtests on your code with Playmatic.
author: Playmatic

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: play
  color: yellow

# Define your inputs here.
inputs:
  api-key:
    description: Your Playmatic API key.
    required: true
  test-url:
    description: The URL of the application to test. Required if environment-id is not provided.
    required: false
  environment-id:
    description: The ID of the Playmatic environment to use for the test. We'll create an environment for the repository by default if not provided
    required: false

# Define your outputs here.
outputs:
  playtest-link:
    description: The URL to view the playtest run.

runs:
  using: node20
  main: dist/index.js
