name: Playmatic Autonomous Test
description: Run autonomous tests on your code with Playmatic.
author: Playmatic

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: play
  color: yellow

# Define your inputs here.
inputs:
  api-key:
    description: Your Playmatic API key from the Settings page of the Playmatic dashboard.
    required: true
  test-url:
    description: The URL of the application to test.
    required: true

# Define your outputs here.
outputs:
  playtest-link:
    description: The URL to view the full test run results.

runs:
  using: node20
  main: dist/index.js
