name: playmatic

on:
  pull_request:
    branches: ["*"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/production' }}

permissions:
  checks: read
  contents: read
  pull-requests: read
  deployments: read

jobs:
  vercel-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.2
        id: vercel-preview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 420
          check_interval: 10
    outputs:
      url: ${{ steps.vercel-preview.outputs.url }}

  start-playtest:
    runs-on: ubuntu-latest
    needs: vercel-preview
    steps:
      - name: Playmatic playtest
        uses: playmaticai/playtest-action@v0.0.3
        with:
          api-key: ${{ secrets.PLAYMATIC_API_KEY_STAGING }}
          test-url: ${{ needs.vercel-preview.outputs.url }}
